/**
 * "Is this lead close to home?" for the `nearby` template flag.
 *
 * Distance is the great-circle (haversine) distance between the Census ZCTA centroids of the lead's
 * ZIP and of the home base ZIP. Both ends are configuration, not code, so moving the operation to
 * another city is an env change and nothing else:
 *   OUTREACH_HOME_BASE_ZIP      (default 01702, Framingham MA)
 *   OUTREACH_HOME_RADIUS_MILES  (default 30)
 * Both are read at call time (cheap), never cached, so a test or a restart-free env change is honoured.
 *
 * Failure policy: anything we cannot establish is `false`. A wrong "nearby" puts a sentence in front
 * of a prospect that is untrue ("we're right around the corner"), which is worse than omitting it.
 *
 * Data: src/server/data/us-zip-centroids.json, regenerated by scripts/generate-zip-centroids.mjs
 * (US Census 2024 Gazetteer ZCTA file). It is a JSON import on purpose: `tsc` copies an imported
 * JSON file into dist/ by itself, so "ships in the production build" needs no extra copy step that
 * could be forgotten.
 */
import zipCentroids from '../data/us-zip-centroids.json'

export const DEFAULT_HOME_BASE_ZIP = '01702'
export const DEFAULT_HOME_RADIUS_MILES = 30

const EARTH_RADIUS_MILES = 3958.8

const centroids = zipCentroids as unknown as Record<string, [number, number] | undefined>

/** A 5-digit ZIP out of a ZIP / ZIP+4 / number value, or null. Numbers are zero-padded (1702 -> 01702). */
export function normalizeZip(value: unknown): string | null {
    if (typeof value === 'number' && Number.isInteger(value) && value >= 0 && value <= 99999) {
        return String(value).padStart(5, '0')
    }
    if (typeof value !== 'string') return null
    const match = /^\s*(\d{5})(?:-\d{4})?\s*$/.exec(value)
    return match ? match[1] : null
}

/**
 * The lead's ZIP. `customFields.zip` / `customFields.postal_code` win when present (non-empty);
 * if one is present but is not a valid ZIP the result is null (no fallback to `location`: an
 * explicit value that is wrong is a data problem, not a reason to guess). Otherwise the LAST
 * 5-digit group (optionally followed by `-dddd`) in `location`.
 */
export function extractLeadZip(
    location: string | null | undefined,
    customFields: Record<string, unknown> | null | undefined,
): string | null {
    for (const key of ['zip', 'postal_code']) {
        const raw = customFields?.[key]
        if (raw == null || (typeof raw === 'string' && raw.trim() === '')) continue
        return normalizeZip(raw)
    }
    if (!location) return null
    const groups = [...location.matchAll(/(?<![\d-])(\d{5})(?:-\d{4})?(?!\d)/g)]
    return groups.length > 0 ? groups[groups.length - 1][1] : null
}

export function haversineMiles(a: [number, number], b: [number, number]): number {
    const toRad = (deg: number) => (deg * Math.PI) / 180
    const dLat = toRad(b[0] - a[0])
    const dLng = toRad(b[1] - a[1])
    const h = Math.sin(dLat / 2) ** 2
        + Math.cos(toRad(a[0])) * Math.cos(toRad(b[0])) * Math.sin(dLng / 2) ** 2
    return 2 * EARTH_RADIUS_MILES * Math.asin(Math.min(1, Math.sqrt(h)))
}

function homeBaseZip(): string {
    return normalizeZip(process.env.OUTREACH_HOME_BASE_ZIP) ?? DEFAULT_HOME_BASE_ZIP
}

function homeRadiusMiles(): number {
    const parsed = Number(process.env.OUTREACH_HOME_RADIUS_MILES)
    return Number.isFinite(parsed) && parsed > 0 ? parsed : DEFAULT_HOME_RADIUS_MILES
}

/** True when `zip` is within the configured radius of the configured home base ZIP. */
export function isZipNearHome(zip: string | null): boolean {
    if (!zip) return false
    const lead = centroids[zip]
    const home = centroids[homeBaseZip()]
    if (!lead || !home) return false
    return haversineMiles(home, lead) <= homeRadiusMiles()
}
